//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Purchases = new HashSet<Purchases>();
        }
    
        public int ClientID { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public decimal Account { get; set; }
        public byte DiscountLevel { get; set; }
        public Nullable<System.DateTime> LastPurchase { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual DiscountLevels DiscountLevels { get; set; }
        public virtual ICollection<Purchases> Purchases { get; set; }
    }
}
