//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountLevels
    {
        public DiscountLevels()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public byte LevelID { get; set; }
        public string Name { get; set; }
        public int AmountOfPurchases { get; set; }
        public decimal PercentDiscount { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
    }
}
