//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyClasses
    {
        public EnergyClasses()
        {
            this.Products = new HashSet<Products>();
        }
    
        public byte EnergyClassID { get; set; }
        public string EnergyClassName { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
