//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.PurchaseItems = new HashSet<PurchaseItems>();
        }
    
        public int ProductID { get; set; }
        public string Model { get; set; }
        public short Category { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<short> Manufacturer { get; set; }
        public Nullable<byte> Color { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<short> Warranty { get; set; }
        public Nullable<short> PowerConsumption { get; set; }
        public Nullable<byte> EnergyClass { get; set; }
        public string Image { get; set; }
        public Nullable<byte> FreezerLocation { get; set; }
        public Nullable<bool> FreshnessZone { get; set; }
        public Nullable<bool> InverterCompressor { get; set; }
        public Nullable<short> RefrigeratorVolume { get; set; }
        public Nullable<short> FreezerVolume { get; set; }
        public Nullable<bool> TemperatureDisplay { get; set; }
        public Nullable<byte> BacklightType { get; set; }
        public Nullable<byte> ScreenSize { get; set; }
        public Nullable<byte> ScreenResolution { get; set; }
        public Nullable<bool> SmartTVSupport { get; set; }
        public Nullable<byte> OperatingSystem { get; set; }
        public Nullable<bool> Bluetooth { get; set; }
        public Nullable<bool> HDRSupport { get; set; }
        public Nullable<byte> WaterConsumption { get; set; }
        public Nullable<byte> NumberOfPrograms { get; set; }
        public Nullable<byte> NumberOfPlacedSets { get; set; }
        public Nullable<byte> LaundryLoad { get; set; }
        public string TemperatureRange { get; set; }
        public Nullable<bool> DirectDrive { get; set; }
        public Nullable<short> MaximumSpinSpeed { get; set; }
        public Nullable<short> InternalVolume { get; set; }
        public Nullable<bool> Grill { get; set; }
    
        public virtual BacklightTypes BacklightTypes { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual EnergyClasses EnergyClasses { get; set; }
        public virtual FreezerLocations FreezerLocations { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual OperatingSystems OperatingSystems { get; set; }
        public virtual ScreenResolutions ScreenResolutions { get; set; }
        public virtual ScreenSizes ScreenSizes { get; set; }
        public virtual ICollection<PurchaseItems> PurchaseItems { get; set; }
    }
}
