//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        public Purchases()
        {
            this.PurchaseItems = new HashSet<PurchaseItems>();
        }
    
        public int PurchaseID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int ClientID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<PurchaseItems> PurchaseItems { get; set; }

        public Clients Clients1
        {
            get => default;
            set
            {
            }
        }
    }
}
